FROM openjdk:11-jre-slim
RUN apt-get update && apt-get -y install wget && rm -rf /var/cache/apt/archives
ENV SCALA_VERSION=2.13
ENV KAFKA_VERSION=3.1.0
ENV FILE_NAME=kafka_${SCALA_VERSION}-${KAFKA_VERSION}
RUN wget -qO- https://dlcdn.apache.org/kafka/${KAFKA_VERSION}/${FILE_NAME}.tgz | tar -xvz
ENV KAFKA_NODE_ID=1
ENV KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
ENV KAFKA_LOG_DIRS=/var/lib/kafka/data
ENV KAFKA_LISTENERS=EXTERNAL://:9092,INTERNAL://:29092,CONTROLLER://:9093
ENV KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
ENV KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:9092,INTERNAL://kafka:29092
ENV KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
ENV KAFKA_LOG_RETENTION_HOURS=168
ENV KAFKA_HEAP_OPTS="-Xms512m -Xmx512m"
COPY start.sh .
CMD ./start.sh

